### ISSUE TITLE
jest-junit does not write compilation errors using ts-jest

### ISSUE THREAD

**Issue by boyanio** [jest-community/jest-junit#116]
I am using the `ts-jest` transformer, so that I can write specs in TypeScript. However, if there are compilation errors, they are not written to the `junit.xml` file. The default Jest reporter does write them to the console.

![image](https://user-images.githubusercontent.com/980463/70037030-87879280-15be-11ea-8cbe-a715f89f6f2c.png)

**Comment by palmerj3** [comment]
Please create a repo where I can easily reproduce this issue and I'll look into it

**Comment by boyanio** [comment]
Hi @palmerj3 Thank you for the quick reply - [here is the repo](https://github.com/boyanio/jest-junit-compilation-errors-issue)

**Comment by palmerj3** [comment]
Thanks @boyanio!

Like I suspected - the issue is that jest does not provide enough info when a test suite completely fails to execute in order for me to responsibly generate a junit.xml file.

Here is [a gist](https://gist.github.com/palmerj3/9d836663e693fb8948087c741320b5d1) of the data jest-junit receives from jest for your sample repo.

For a junit.xml file you expect that test suites and test cases will remain stable across test runs (e.g. the name doesn't change) so you can store this metadata for your test runs - like if you wanted to track how long a particular test case takes to run, determine if tests are flaky, etc.

In the case where a test suite completely fails to run there are no uniquely identifying information about the test suite(s) for me to produce a junit.xml file. If i did produce one it would just be a single test suite with a name I make up - it would not conform to your jest-junit settings and likely would not match any existing metadata you may have about that test suite. This is also complicated by the fact that you can have multiple test suites in a single file (each top level describe block is a test suite).

So all of this is to say: this is not something within jest-junit's control so this is currently not something that can be addressed.
