### ISSUE TITLE
Override jest-junit default output location?

### ISSUE THREAD

**Issue by matsev** [jest-community/jest-junit#119]
How can I override the default output directory and file name [jest-junit][1]?

I would like to customise the output configuration of  output when using Jest, but it still ends up in the default location, i.e. `./junit.xml` in the project root folder. 

---
### My configuration

In _package.json_:

      "scripts": {
        "test": "jest --ci --reporters=default --reporters=jest-junit",
      },
      "devDependencies": {
        "jest": "^24.9.0",
        "jest-junit": "^10.0.0",
      }

In _jest.config.js_

    module.exports = {
      testMatch: [
        '**/*.spec.js',
      ],
      reporters: [
        'default',
        [ 'jest-junit', {
          outputDirectory: 'test_reports',
          outputName: 'jest-junit.xml',
        } ]
      ]
    };

### Expected result:

 - A file with the test result at `./test_reports/jest-junit.xml`

### Actual result:

 - A file with the test result at the default `./junit.xml`

--- 

### Comment

If I add the configuration to the `package.json` file instead (see below), the XML file is generated in the desired location:

    "jest-junit": {
      "outputDirectory": "test_reports",
      "outputName": "jest-junit.xml"
    },

  [1]: https://github.com/jest-community/jest-junit#readme

**Comment by palmerj3** [comment]
Hi @matsev thanks for submitting an issue!

I am unable to reproduce this locally. When I copy your jest.config.js file and run a test suite I get the test_reports folder and a file named jest-junit.xml inside it.

Could you please create a repository on github where this issue is reproduced so I can look into this further?

Thanks!

**Comment by matsev** [comment]
Thanks for the rapid response. I have created a GitHub repo that you can use for debugging:

https://github.com/matsev/debug-jest-junit-config

**Comment by palmerj3** [comment]
Thank you!

So the issue is that you specify reporters both in jest.config.js and in the cli for your "test" script in package.json.

If you remove `--reporters=default --reporters=jest-junit` from package.json it works as expected.

Jest prioritizes cli configuration so if you have that it will override any other option. And in this case it was overriding the "reporters" option.

**Comment by matsev** [comment]
@palmerj3 Thanks for taking the time to investigate this!
