### ISSUE TITLE
Upgrade mkdirp to the latest version

### ISSUE THREAD

**Issue by JimmyBjorklund** [jest-community/jest-junit#124]
Upgrade mkdirp to the latest version due to:
https://github.com/advisories/GHSA-7fhm-mqm4-2wp7

I have added pull request for this but, it requires drop of node 8 support.

**Comment by JimmyBjorklund** [comment]
If you dont want to drop node 8, this might work fs.mkdirSync using {recursive: true}

**Comment by JimmyBjorklund** [comment]
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x.

**Comment by opiation** [comment]
`jest` has [dropped node 8 support][releases] for [v26.0.0][v26] so that's a good motivator for those still using node 8.  I guess this depends on what versions of `jest` the maintainers here want to consider _actively supported_.  Since jest v25 still supports node 8, it may yet be a while.

[releases]: https://github.com/facebook/jest/releases/tag/v26.0.0
[v26]: https://github.com/facebook/jest/blob/v26.0.0/package.json#L132

**Comment by palmerj3** [comment]
This has been done for jest-junit 11.0.0
