### ISSUE TITLE
[Feature] output without stack trace.

### ISSUE THREAD

**Issue by nesless** [jest-community/jest-junit#136]
I don't think there is any option not to include stack trace in output file.

F.E. doesn't include following stack trace:

 at Object.&lt;anonymous&gt; (/Users/someone/src/__tests__/index.test.js:39:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by palmerj3** [comment]
I'm not sure I understand what you're reporting here.

Please describe the issue and then provide a repository that reproduces the problem and I'll have a look.

**Comment by sginter** [comment]
I think I have the same problem :-)

So, what I need is:
```
<testcase classname="additional test" name="case 1" time="0.004">
   <failure>Error: expect(received).toEqual(expected) // deep equality

Expected: 2
Received: 6
</failure>
```

What I get is:
```
<testcase classname="additional test" name="case 1" time="0.004">
   <failure>Error: expect(received).toEqual(expected) // deep equality

Expected: 2
Received: 6
at [stack trace element]
at [stack trace element]
...
</failure>
```

It comes from https://github.com/jest-community/jest-junit/blob/3eb8b0270f42da5c8585327ac6246a16f4c0decd/utils/buildJsonResults.js#L189
(adding tc.failureMessages instead of tc.failureDetails[].message without the tc.failureDetails[].stack appended)

Sorry, I don't know the code base, but it seems to come from jest (actually, is it jest-jasmine reporter.js?) and it seems that it includes the stack trace despite the `--noStackTrace` param passed to jest. I assume it means its reporter's job to include the stack or not :-)

I would gladly come back with a pull request, but please advise how to approach it?
Additional option similar to includeConsoleLog?
includeStackTraces defaulting to true?

**Comment by palmerj3** [comment]
That's a good point. I'm not sure how that feature of jest works.. but if jest-junit gets the output for the failure message we're going to show it.

I suspect this is an issue or a misunderstanding with how Jest handles that CLI flag.

I'd be happy if you investigate it further. I suspect the issue is on the jest side not on the jest-junit side.
But I'm always happy to accept PRs.
