### ISSUE TITLE
Support possible injected values in all config options such as `suiteName`, `outputName`, `outputDirectory`

### ISSUE THREAD

**Issue by leandrocrs** [jest-community/jest-junit#174]
I'm using jest-junit inside a [NX](https://nx.dev) monorepo and to me is a killer feature to name all my tests results in such way using projects names like:
```
tests-results/junit-app.xml
tests-results/junit-core.xml
...
```

**Comment by palmerj3** [comment]
That's already possible. The "displayName" property refers to the jest project name and you can use that within suiteName, outputName, etc.

**Comment by Pouja** [comment]
If I configure `jest-junit` with:
```js
module.exports = {
  projects: [
    {
      displayName: "Unit Tests",
      testMatch: ["<rootDir>/__tests__/**/*.js"],
      testPathIgnorePatterns: [
        '<rootDir>/node_modules/',
        '<rootDir>/__tests__/lib'
      ],
      testEnvironment: 'node',
      setupFilesAfterEnv: ["<rootDir>/__tests__/lib/setupTests.js"]
    },
    "<rootDir>/integration-tests/testResultsProcessor/",
    "<rootDir>/integration-tests/reporter/"
  ],
  reporters: ['default', ['.', {
    outputName: 'jest-{displayName}.xml',
  }]]
};
```
It will literally output a file `jest-{displayName}.xml`

Also looking at https://github.com/jest-community/jest-junit/blob/master/utils/getOutputPath.js#L9 it seems it takes the raw configuration.

**Comment by palmerj3** [comment]
Ah you're right I'm sorry I gave you the wrong information.

Currently jest-junit doesn't allow for injection variables for the path locations.

However it will create a junit.xml file at the root of a jest project for each project. So you could have a post-test npm script or something like that that can rename the files as you need.

Let me know if that will suffice.

**Comment by Pouja** [comment]
Oh no problem!
In the case of @nrwl/nx that would not work because it runs jest parallel on all the projects. So the junit.xml will be overwritten per project. One way to solve this is by using `uniqueOutputName` but I am not sure at the moment if that would solve my problem that I am facing. Which is to concatenate the test results of the previous CI with the test results of the projects that are changed in my current commit.

But if I do require the displayName in the file output, that would be a bit difficult since jest can input multiple projects each with their own displayName. In that case you would need to split the single output xml file per given context in https://github.com/jest-community/jest-junit/blob/master/index.js#L78

**Comment by schmkr** [comment]
Also using Nx here and found a workaround leveraging environment variables and some assumptions (but should be doable to build upon).

I found out that the project being tested when running it via `nx affected:test` or `nx test <project name>` is available under the environment variable `NX_TASK_TARGET_PROJECT`.

That variable could then be used to construct a unique `outputDirectory` per project.

By default, Nx generates a configuration for the `test` target with an `outputs` set to:

```
"outputs": ["coverage/libs/<dir and name of the project>"],
```

which is where code coverage reporting will be generated. That outputs list is necessary for Nx for its caching logic. If you generate files not listed in that list of `outputs` and the same task for the project is restored from cache, the report will be missing.

You can then choose to either add an additional directory in each project configuration where the junit report will be generated, or set the `outputDirectory` to that of the coverage reporting. I choose the latter, because newly added projects will then also require manual work to add that extra directory too (or you would need to create your own generator for this).

That being said, I created this in `jest.preset.js`:

```js
const path = require('path');
const nxPreset = require('@nrwl/jest/preset');
const {projects} = require(path.resolve(__dirname, 'workspace.json'));

const reporters = ['default', [
  'jest-junit',
  {
    outputDirectory: `coverage/${projects[process.env['NX_TASK_TARGET_PROJECT']]}`,
    suiteNameTemplate: ({ filepath }) => filepath,
  },
]];

module.exports = {
  ...nxPreset,
  // rest of customization

  reporters
};
```

Currently, the `workspace.json` is a map of projects referencing their locations, like so:

```json
{
  "version": 2,
  "projects": {
    "core-auth": "libs/core/auth",
    "core-http": "libs/core/http",
    "core-storage": "libs/core/storage",
    "login-feature-login": "libs/login/feature-login",
    "shared-i18n": "libs/shared/i18n",
    "shared-utils": "libs/shared/utils",
    "testing-mocks": "libs/testing/mocks",
    "ui-components": "libs/ui/components",
    "webapp": "apps/webapp",
    "webapp-e2e": "apps/webapp-e2e",
  }
}
```

The jest.preset.js snippet now maps the project name to the location from workspace.json (or angular.json). You could also use that location to require the project.json and parse the `test` target `outputs` key to find the location where to store the junit report. In our setup (and I think most other as well), that will actually be `coverage/libs/core/auth` anyway. So I skipped that last step.

Hope this helps!

**Comment by juan-belmonte** [comment]
Now that recent Nx versions do not include the `workspace.json` file, I'll share this solution that works for me in case it's useful for someone else:

```ts
const { readCachedProjectConfiguration } = require('nx/src/project-graph/project-graph');
const nxPreset = require('@nrwl/jest/preset').default;

const currentModuleName = process.env.NX_TASK_TARGET_PROJECT;
const workspaceRoot = process.env.NX_WORKSPACE_ROOT;

const configuration = readCachedProjectConfiguration(currentModuleName);
const moduleFolder = configuration.sourceRoot.replace('/src', '');
const jUnitOutputDirectory = `${workspaceRoot}/coverage/${moduleFolder}`;

module.exports = {
  ...nxPreset,
  reporters: [
    'default',
    ['jest-junit', { outputDirectory: jUnitOutputDirectory, outputName: 'junit-result.xml' }]
  ]
};
```

Although probably it's not the cleanest way to achieve it, it works for me.
