### ISSUE TITLE
Include FileName in gitlab CI

### ISSUE THREAD

**Issue by MoreiraJorge** [jest-community/jest-junit#198]
I'm having a problem where i cant include the file name in the test report in gitlab CI. I see no attribute in the doc specific to this field. Can someone help? Thanks.

#### Jest-Junit config in package.json

```
"jest-junit": {
    "suiteName": "Trust api jest tests",
    "suiteNameTemplate": "{title}",
    "classNameTemplate": "{classname}",
    "titleTemplate": "{title}",
    "outputFile": "./coverage/junit.xml",
    "uniqueOutputName": "false",
    "ancestorSeparator": " › ",
    "includeShortConsoleOutput": true,
    "reportTestSuiteErrors": true,
    "noStackTrace": false
  },
```
#### Empty filename
<img width="1205" alt="Screenshot 2022-01-27 at 17 04 51" src="https://user-images.githubusercontent.com/32751407/151408681-3deda7e6-e8fc-45ca-85b7-117d5a338047.png">

#### Packages/ frameworks versions: 
node v17.3.0
nestjs/common - 8.2.5
nestjs/core - 8.2.5
jest - 27.0.6
jest-junit - 13.0.0

**Comment by palmerj3** [comment]
Hey thanks for submitting an issue!

I'm going to need more information.

Are you saying that you're unable to change the filename from junit.xml to something else?
Or are you saying that you want to be able to use your chosen filename as an attribute you can include in the junit xml itself (such as in the classname)?

**Comment by MoreiraJorge** [comment]
Hi! Thanks for the reply!
I think the second one :)
I was wondering if i could add the file name since in gitlab there is a Filename field in the report (after being parsed as you can see in the image, between name and status), but is empty.

I don't know if it is supposed to be there. I don't see any option in the docs related to that field, and if it is supposed to be there how can i edit it?

**Comment by palmerj3** [comment]
Ok understood.

Right now that is not supported.

And we're unable to add the filename field because there is nothing in the jenkins junit xsd that mentions this. So if we added it - it would fail a lot of folks builds on other platforms. https://github.com/jest-community/jest-junit/blob/master/__tests__/lib/junit.xsd

You could hardcode your junit output path in testsuite or something like that if you like.

Example jest config:
```
module.exports = {
  reporters: ['default', [
    'jest-junit',
    {
      suiteName: '/path/to/junit.xml Jest tests'
    }
  ]]
}
```

This would output something like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="/path/to/junit.xml Jest tests" tests="1" failures="0" errors="0" time="0.281">
  <testsuite name="foo" errors="0" failures="0" skipped="0" timestamp="2022-01-27T18:20:52" time="0.234" tests="1">
    <testcase classname="foo should foo" name="foo should foo" time="0.001">
    </testcase>
  </testsuite>
</testsuites>
```

**Comment by palmerj3** [comment]
You could always have a post-test npm script that adds this field if absolutely necessary.

But given that gitlab's documentation says to use jest-junit in a pretty stock way I'm not sure exactly what this would add for you.

https://docs.gitlab.com/ee/ci/unit_test_reports.html#jest

**Comment by palmerj3** [comment]
Actually. Please ignore EVERYTHING I wrote haha.

I looked more closely at the screenshot and I believe it's looking for you to have the path to the test file itself.

That can be added pretty easily.

Give this config a try:

```
module.exports = {
  reporters: ['default', [
    'jest-junit',
    {
      suiteNameTemplate: '{filepath}'
    }
  ]]
}
```

Outputs junit like this which will hopefully fill out that field properly. If it doesn't then play around with suiteNameTemplate and/or classNameTemplate options we offer in jest-junit and you should be able to make something work.

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="1" failures="0" errors="0" time="0.209">
  <testsuite name="__tests__/foo.test.js" errors="0" failures="0" skipped="0" timestamp="2022-01-27T18:34:55" time="0.171" tests="1">
    <testcase classname="foo should foo" name="foo should foo" time="0.001">
    </testcase>
  </testsuite>
</testsuites>
```

**Comment by andorfermichael** [comment]
I would appreciate it too.

`suiteNameTemplate: '{filepath}'` unfortunately does not work for me

**Comment by andorfermichael** [comment]
I have found the solution based on the following [source](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/44802):

You have to add: 

```
"jest-junit": {
    addFileAttribute: 'true',
}
```

Maybe the [readme section "configuration"](https://github.com/jest-community/jest-junit#configuration) should be updated, because currently, it says that this option is primarily for Circle CI.

**Comment by palmerj3** [comment]
Ah cool! Would you mind submitting a PR to update the docs?

**Comment by MoreiraJorge** [comment]
I'm sorry for the late reply guys. This code:
```
"jest-junit": {
    addFileAttribute: 'true',
}
```

worked perfectly! Thanks @andorfermichael @palmerj3

**Comment by SimenB** [comment]
`'true'` as a string? That looks off 😛

**Comment by palmerj3** [comment]
Been a while since I worked on this bit of code but I believe it has to do with the fact that you can configure jest-junit in package.json, jest config, via reporter arguments, and also via environment variables or any combination thereof.

So not all of those have the ability to have strict boolean values and strings are the easiest thing to normalize.
