### ISSUE TITLE
output: Support <rootDir>

### ISSUE THREAD

**Issue by mfulton26** [jest-community/jest-junit#49]
Whenever I run a single test via IntelliJ IDEA (also applies to WebStorm) the resulting `junit.xml` is created in the directory where the test file exists instead of at the root of my project.

It would be great if `"output"` supported something like Jest's `"<rootDir>"` which several of its path-like options support (see https://facebook.github.io/jest/docs/en/configuration.html).

e.g. **package.json** snippet:

```json
  "jest-junit": {
    "output": "<rootDir>/junit.xml"
  }
```

`"<rootDir>/junit.xml"` would also probably be a sensible default rather than `"./junit.xml"`.

Thank you.

**Comment by palmerj3** [comment]
I'll look into this - great idea!

**Comment by IIFE** [comment]
Any news on this?
It will be very useful when working in a monorepo, where instead of having to define the output of jest-junit in the jest.config for each project, it can be defined in the base jest.config, in the form of:
reporters: [ "default", ["jest-junit", { "output": "<rootDir>/test-results/result.xml" }] ]

This will work because in a monorepo rootDir will be referring to the project under test. Currently I'm having to do the above in each project.

Thanks.

**Comment by SimenB** [comment]
PR welcome! 🙂
