### ISSUE TITLE
Why is testResultsProcessor support deprecated?

### ISSUE THREAD

**Issue by johngrogg** [jest-community/jest-junit#56]
I'm wondering why `jest --ci --testResultsProcessor="jest-junit"` is a deprecated pattern? It's super useful to set the results processor at the command line for CI environments (no need to have the junit file artifact generated when running tests locally).

**Comment by sarod** [comment]
@johngrogg I don't know why result processor is deprecated.

However if you want to avoid generating the junit file in dev you can have a jest config dedicated for CI environment that overrides the reporters config.

Here is an example of `jest.config.ci.js` that replaces the "reporters"
```javascript
const baseConfig = require('./jest.config');

module.exports = {
   ...baseConfig,
   "reporters": [ "jest-junit"]
}
```

Then you run `jest --ci --config=jest.config.ci.js` in your CI environement.

**Comment by palmerj3** [comment]
@johngrogg it's deprecated because testResultsProcessor will eventually be removed from Jest and I wanted to start preparing jest-junit users to switch to reporters. Reporters and testResultsProcessor offers almost exactly the same API.

Another compelling reason is @sarod recent feature. I'm sure there will be more like this. The reporter API offers the ability to use functions for configuration whereas a testResultsProcessor doesn't offer this capability.

So what I would recommend is either trying multiple jest configs (one for local one for CI) or utilize the CI environment variable and have a jest config that reacts to the presence of this environment variable.

**Comment by johngrogg** [comment]
@palmerj3 Ahh, that makes sense now. I hadn't seen anything in the jest documentation about that being eventually removed from Jest.

I also hadn't thought about using specific config files (I've just been using the package.json "jest" section). Thanks for the advice. You may want to update the documentation of this with a simple example of how to do what @sarod described above.
