### ISSUE TITLE
Junit log errors

### ISSUE THREAD

**Issue by MRolandd** [jest-community/jest-junit#85]
How to display syntax errors in Junit log? Or exactly how does the` <error>` tag appear? If I fail a test it is a` <failure>`. 
In PHP unit the` <error>` tag appears when There is a syntax error

**Comment by palmerj3** [comment]
@MRolandd currently jest does not differentiate between an "error" and a "failure" so currently that portion is unused.

It's a feature I've wanted to add to jest for a while and eventually will do - it's a bit complex of a change in jest to make that happen.

**Comment by MRolandd** [comment]
Ok, then it is a way to parse syntax errors from the code as failures? If I have a syntax error my log file is empty. Just with an empty

**Comment by palmerj3** [comment]
Well syntax errors and other non-recoverable errors like this result in jest not even successfully parsing  the test file. So, in this case, a reporter (any reporter) wouldn't get enough useful information to be able to generate a report.

jest-junit, in particular, would need to know the describe and/or it block names otherwise we'd be reporting on failures/errors on some generated id and you might not be able to make a connection to the actual test file.

**Comment by MRolandd** [comment]
Thank you for your reply. It really helped about this issue.
